### ISSUE TITLE
Possible wrong code for Ice Pellets on Metar.php

### ISSUE THREAD

**Issue by Celinium** [hsdn/metar-taf#1]
After few tests with this PHP script (Thank you BTW for sharing it), I came to the conclusion the code for Ice Pellets is not the right one. More precisely, on line #143 the code : 
'PE' => 'ice pellets',
should be replaced by 
'PL' => 'ice pellets',

Here is sample METAR for Montreal I used : CYUL 081236Z 15019G24KT 4SM -FZDZ -PL DRSN OVC020 M02/M05 A2978 RMK NS8 SLP087

**Comment by justkeepquiet** [comment]
Hi. This fixed now https://github.com/hsdn/metar-taf/commit/dd996b54f0d2b2ca42c62315ebf34c999832cffa. Thanks for contribuion.
